FROM ubuntu:22.04

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

RUN apt update && apt upgrade -y

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

COPY ./app.conf /tmp/app.conf

WORKDIR /var/www/app
EXPOSE 4200/tcp

RUN apt install -q -y curl npm
RUN npm config set strict-ssl false
RUN npm cache clean -f
RUN npm install -g n
RUN n 18
RUN npm install -g @angular/cli

# apache
RUN apt install apache2 -q -y
RUN a2enmod rewrite
RUN a2enmod headers
RUN a2enmod proxy proxy_http
RUN a2enmod ssl

RUN cp /tmp/app.conf /etc/apache2/sites-available/app.conf
RUN a2dissite 000-default.conf
RUN rm -rf /var/www/html
RUN a2ensite app.conf
